### ISSUE TITLE
exception.hpp: warning C4265 given by Visual Studio

### ISSUE THREAD

**Issue by bersbersbers** [boostorg/exception#23]
This has been reported before (https://svn.boost.org/trac10/ticket/13227), but I am not sure that tracker is still active. The problem is still relevant with boost 1.65.1 and 1.70.

Quoting:

> MSVC falsely report a missing virtual destructor inside exception.hpp Would it be possible to add a "pragma warning (disable:4265)" in this file ? This will *not* happen with the default settings of Visual Studio : it happens when trying to raise the warning level (/we4265 : treat "misssing virtual destructor" as an error)

The above link has reproduction steps, in particular, https://github.com/ivsgroup/boost_warnings_minimal_demo

**Comment by zajo** [comment]
Sorry I had missed this. See https://github.com/boostorg/throw_exception/commit/43a57d518cf99fc693eebedefcbaa91074674f54

**Comment by Shawn1874** [comment]
I know this is closed, but the warning / error doesn't appear to be a false report.  Instead of disabling the warning, shouldn't the destructor have been made virtual?

**Comment by zajo** [comment]
It is incorrect for this destructor to be virtual. The destructor is never called via a pointer to the base type.

**Comment by Shawn1874** [comment]
As a general rule classes with virtual methods ought to have a virtual destructor which is the reason for the warning.  It certainly wouldn't hurt anything for the the destructor to be virtual.  There is nothing incorrect about a virtual, protected method.  It seems like it was more of a preference for someone to disable the warning.

**Comment by zajo** [comment]
It is a deliberate design decision. Marking a function virtual indicates dynamic polymorphism. In this design, calling the destructor polymorphically would be a logic error. In C++, this is communicated by declaring the destructor protected and non-virtual.
