### ISSUE TITLE
Unreal Engine 5 build error

### ISSUE THREAD

**Issue by egorpugin** [boostorg/exception#47]
https://github.com/boostorg/exception/blob/develop/include/boost/exception/detail/exception_ptr.hpp#L29

All lines with GNUC ifdef like this fails with error:
```
boost\exception\exception.hpp(22): error C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
boost\exception\exception.hpp(22): error C4668: '__GNUC_MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

Possible fix - https://github.com/boostorg/smart_ptr/pull/98
Such change should be implemented with all occurences of `__GNUC__`

Probably this repo is also affected.
https://github.com/boostorg/throw_exception

**Comment by zajo** [comment]
This is likely due to excessive warnings level. It is standard and correct behavior that undefined macros used in preprocessor expressions evaluate to 0.
