### ISSUE TITLE
unresolved external symbol "void __cdecl boost::throw_exception with VS2019

### ISSUE THREAD

**Issue by sthalasayanam** [boostorg/exception#52]
I get the compiler error unresolved external symbol "void __cdecl boost::throw_exception in VS2019 even if I have the custom function

namespace boost{
#ifdef BOOST_NO_EXCEPTIONS
	template<class E>
	void throw_exception(E const& e) {
	//do nothing
}
#endif
}

**Comment by zajo** [comment]
There are two issues with your function:

First, it may not be a template. It should just take a `std::exception const &`.

Secondly, it is not allowed to return, so can't "do nothing". Call terminate or throw an exception, those are your choices.
